# Generated by Django 3.1.4 on 2022-02-24 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.storage_config


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_id', models.CharField(editable=False, max_length=16)),
                ('file', models.FileField(storage=files.storage_config.PrivateMediaStorage(), upload_to='uploads/')),
                ('thumbnail', models.FileField(null=True, storage=files.storage_config.PrivateMediaStorage(), upload_to='uploads/')),
                ('micro_thumbnail', models.FileField(null=True, storage=files.storage_config.PrivateMediaStorage(), upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('file_size', models.IntegerField(null=True)),
                ('file_type', models.CharField(max_length=50, null=True)),
                ('file_extension', models.CharField(max_length=25, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
