# Generated by Django 3.1.4 on 2022-02-25 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationcustomer'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_id', models.CharField(blank=True, max_length=32)),
                ('fee_number', models.CharField(blank=True, max_length=16)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_config_id', models.CharField(blank=True, max_length=16)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('day', models.IntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('structure', models.CharField(choices=[('flat-fee', 'Flat Fee'), ('principle-percentage', 'Percentage of Principal'), ('loan-percentage', 'Percentage of Loan Amount')], max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interest_id', models.CharField(blank=True, max_length=32)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interest_config_id', models.CharField(blank=True, max_length=16)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('day', models.IntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('config', models.CharField(choices=[('principle-percentage', 'Percentage of Principal'), ('loan-percentage', 'Percentage of Loan Amount'), ('flat-fee', 'Flat Fee')], max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_id', models.CharField(blank=True, max_length=32)),
                ('loan_number', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('void', 'Void'), ('cleared', 'Cleared'), ('overdue', 'Overdue'), ('default', 'Default')], default='active', max_length=25)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(blank=True, max_length=32)),
                ('payment_number', models.CharField(blank=True, max_length=16)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_config_id', models.CharField(blank=True, max_length=16)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('day', models.IntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('structure', models.CharField(choices=[('flat-amount', 'Flat Amount'), ('principle-percentage', 'Percentage of Principal'), ('loan-percentage', 'Percentage of Loan Amount')], max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=16)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=32)),
                ('transaction_number', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('interest', 'Interest'), ('fee', 'Fee')], default='applied', max_length=25)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('voided', 'Voided')], default='applied', max_length=25)),
                ('fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.fee')),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.interest')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.payment')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_config_id', models.CharField(blank=True, max_length=16)),
                ('length', models.IntegerField()),
                ('overdue_on_day', models.IntegerField()),
                ('default_on_day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('fee_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.feeconfig')),
                ('interest_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.interestconfig')),
                ('payment_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.paymentconfig')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allow_multiple_loans', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.productconfig'),
        ),
    ]
