# Generated by Django 3.1.4 on 2022-02-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_product_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationsettings',
            old_name='allow_multiple_loans',
            new_name='multiple_loans_per_customer',
        ),
    ]
