# Generated by Django 3.1.4 on 2022-02-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20220225_0652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationSettings',
        ),
    ]
