# Generated by Django 3.1.4 on 2022-02-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20220225_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productconfig',
            name='fee_config',
        ),
        migrations.RemoveField(
            model_name='productconfig',
            name='interest_config',
        ),
        migrations.RemoveField(
            model_name='productconfig',
            name='payment_config',
        ),
        migrations.AddField(
            model_name='feeconfig',
            name='product_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.productconfig'),
        ),
        migrations.AddField(
            model_name='interestconfig',
            name='product_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.productconfig'),
        ),
        migrations.AddField(
            model_name='loan',
            name='product_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.productconfig'),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='product_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.productconfig'),
        ),
    ]
