# Generated by Django 3.1.4 on 2022-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20220225_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfig',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25),
        ),
    ]
