# Generated by Django 3.1.4 on 2022-02-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_productconfig_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestconfig',
            old_name='config',
            new_name='structure',
        ),
    ]
